//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiThu_MVC_61133801.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KT0720_MVC_61133801Entities : DbContext
    {
        public KT0720_MVC_61133801Entities()
            : base("name=KT0720_MVC_61133801Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOP> LOP { get; set; }
        public virtual DbSet<SINHVIEN> SINHVIEN { get; set; }
    }
}
